[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"

[env]
DATABASE_URL = "postgresql://neondb_owner:npg_o9XGQhSY0Pgf@ep-dark-rain-apyozkkj-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
