[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node index.js"

[env]
DATABASE_URL = "postgresql://xata:xIpmyAjz9I0Hb3rWE6m2MYDyUMCmc9hY2rnPgfoi6eejjwGlN9KuXrLfVmbHnsG2@ma8pq7vand7rv3dvpeaa1kdbog.us-east-1.xata.tech/xata?sslmode=require"