services:
  - type: web
    name: tell
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_o9XGQhSY0Pgf@ep-dark-rain-apyozkkj-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"